openapi: 3.0.0
info:
  title: T-Shirt Store Application
  description: Swagger documentation for T-Shirt-Store Project
  version: 1.1.0
  contact:
    email: kankit08@gmail.com

servers:
  - url: "{protocol}://localhost:8000/api/{version}"
    description: for local host
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /dummy:
    get:
      tags:
        - String
      summary: returns a greet message
      responses:
        200:
          descrption: All good and success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad Request
        500:
          description: Internal Server Error
